### PR TITLE
Update playerconfig.h

### PR DESCRIPTION
**Pull request by ArjunGemeray**

### CODE REVIEW

**Comment by Spritetm** [comment]
...okay, why would it be a good idea to merge this? Pressed the 'pull request' accidentally I presume?

**Comment by ArjunGemeray** [comment]
how can i upload esp8266 mp3 decoder program on esp8266
please guide me.

**Comment by Spritetm** [comment]
Please read the docs in the repo.

**Comment by ArjunGemeray** [comment]
hi, I do not understand the docs how to upload mp3 decoder firmware in
esp8266 and what software is used to convert the master decoder into
firmware.please guide me.

**Pull request closed without merging**
